Pages/AddProduct.cshtml.cs
using InventorySystem.Data;
using InventorySystem.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Reflection.Metadata;

namespace InventorySystem.Pages
{
    public class AddProductModel : PageModel
    {
        private readonly InventoryDbContext inventoryDbContext;
        [BindProperty]
        public Product Product { get; set; }
        public List<InventorySystem.Models.Branch> Branches { get; set; }

        public AddProductModel(InventoryDbContext InventoryDbContext)
        {
            this.inventoryDbContext = InventoryDbContext;
        }
        public void OnGet()
        {
            if(HttpContext.Session.GetString("LoggedInUserName").Equals("Admin"))
            {
                Branches = inventoryDbContext.Branch
                .Where(branch => branch.Name != "Admin")
                .ToList();
            }
        }
        public async Task<IActionResult> OnPostAsync()
        {
            if (!HttpContext.Session.GetString("LoggedInUserName").Equals("Admin"))
            {
                Product.Location = HttpContext.Session.GetString("LoggedInLocation");
                Product.BranchId = inventoryDbContext.User.SingleOrDefault(u => u.UserName.Equals(HttpContext.Session.GetString("LoggedInUserName"))).BranchId;
            }

            else
            {
                Product.Location = inventoryDbContext.Branch.Find(Product.BranchId).Name;
            }
            ModelState.Remove("Product.Location");

            if (ModelState.IsValid)
            {
                inventoryDbContext.Product.Add(Product);
                await inventoryDbContext.SaveChangesAsync();
                return RedirectToPage("/MainPage");
            }
            else
            {
                return Page();
            }
        }
    }
}

Pages/EditProduct.cshtml.cs
using InventorySystem.Data;
using InventorySystem.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Reflection.Metadata.Ecma335;

namespace InventorySystem.Pages
{
    public class EditProductModel : PageModel
    {
        [BindProperty]
        public Product EditProduct { get; set; }
        private readonly InventoryDbContext inventoryDbContext;

        public EditProductModel(InventoryDbContext inventoryDbContext)
        {
            this.inventoryDbContext = inventoryDbContext;
        }
        public void OnGet(int Id)
        {
            var product = inventoryDbContext.Product.Find(Id);

            if (product != null)
            {
                EditProduct = new Product()
                {
                    Id = product.Id,
                    BranchId = product.BranchId,
                    Name = product.Name,
                    Description = product.Description,
                    ProductId = product.ProductId,
                    Quantity = product.Quantity,
                    PriceCustomer = product.PriceCustomer,
                    PriceImporter = product.PriceImporter,
                    Location = product.Location,
                    Threshold = product.Threshold,
                };
            }
        }
        public void OnPostUpdate(int Id)
        {
            if (EditProduct != null)
            {
                var existingProduct = inventoryDbContext.Product.Find(Id);
                if (existingProduct != null)
                {
                    existingProduct.Description = EditProduct.Description;
                    existingProduct.Quantity = EditProduct.Quantity;
                    existingProduct.PriceCustomer = EditProduct.PriceCustomer;
                    existingProduct.Threshold = EditProduct.Threshold;
                    inventoryDbContext.SaveChanges();
                    ViewData["Message"] = "Product Updated";
                }
            }
        }
        public IActionResult OnPostDelete(int Id)
        {
            var existingProduct = inventoryDbContext.Product.Find(Id);
            if (existingProduct != null)
            {
                inventoryDbContext.Product.Remove(existingProduct);
                inventoryDbContext.SaveChanges();
                return RedirectToPage("/InventoryUpdate");
            }
            return Page();

        }

    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace WebApplication1.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace InventorySystem.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Pages/InventoryUpdate.cshtml.cs
using InventorySystem.Data;
using InventorySystem.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace InventorySystem.Pages
{
    public class InventoryUpdateModel : PageModel
    {
        private readonly InventoryDbContext inventoryDbContext;
        [BindProperty]
        public Product Product { get; set; }
        public List<InventorySystem.Models.Product> Products { get; set; }  
        public InventoryUpdateModel(InventoryDbContext inventoryDbContext)
        {
            this.inventoryDbContext = inventoryDbContext;
        }
        public String productAddress;

        public void OnGet(string sortOrder)
        {
            var loggedInUserName = HttpContext.Session.GetString("LoggedInUserName");
            var loggedInLocation = HttpContext.Session.GetString("LoggedInLocation");
            IQueryable<InventorySystem.Models.Product> productsQuery;

            if (loggedInUserName.Equals("Admin"))
            {
                productsQuery = inventoryDbContext.Product;
            }
            else
            {
                var branchId = inventoryDbContext.Branch.SingleOrDefault(b => b.Name.Equals(HttpContext.Session.GetString("LoggedInLocation"))).Id;
                productsQuery = inventoryDbContext.Product.Where(p => p.BranchId.Equals(branchId));
            }
                switch(sortOrder)
            {
                case "name":
                    productsQuery = productsQuery.OrderBy(p => p.Name);
                    break;
                default:
                    productsQuery = productsQuery.OrderByDescending(p => p.ProductId);
                    break;

            }
            Products = productsQuery.ToList();
        }
    }
}

Pages/LoginPage.cshtml.cs
using System.Linq;
using InventorySystem.Data;
using InventorySystem.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;


namespace InventorySystem.Pages
{
	public class LoginPageModel : PageModel
	{
		private readonly InventoryDbContext inventoryDbContext;

		[BindProperty]
		public User UserLogin { get; set; }

		public LoginPageModel(InventoryDbContext inventoryDbContext)
		{
			this.inventoryDbContext = inventoryDbContext;
		}

		public void OnGet()
		{
		}

		public IActionResult OnPost()
		{
			// Check if the user with the given credentials exists in the database
			var user = inventoryDbContext.User
				.FirstOrDefault(u => u.UserName == UserLogin.UserName && u.Password == UserLogin.Password);

			if (user != null)
			{
				HttpContext.Session.SetString("LoggedInUserName", user.UserName);
				if (!HttpContext.Session.GetString("LoggedInUserName").Equals("Admin"))
					HttpContext.Session.SetString("LoggedInLocation", inventoryDbContext.Branch.Find(user.BranchId).Name); 

                return RedirectToPage("/MainPage");
			}
			else
			{
               // show an error message
                ViewData["Message"] = "Invalid Username or Password";

				return Page();
			}
		}

		public IActionResult OnPostLogout()
		{
			HttpContext.Session.Remove("LoggedInUserName");
			HttpContext.Session.Remove("LoggedInLocation");
            return RedirectToPage("/Index");
        }
    }
}

Pages/MainPage.cshtml.cs
using InventorySystem.Data;
using InventorySystem.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace InventorySystem.Pages
{
    public class MainPageModel : PageModel
    {
       
        public void OnGet()
        {
        }
    }
}

Pages/ProductsInChain.cshtml.cs
using InventorySystem.Data;
using InventorySystem.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace InventorySystem.Pages
{
    public class ProductsInChainModel : PageModel
    {
        private readonly InventoryDbContext inventoryDbContext;

        public class BranchProductViewModel
        {
            public Branch Branch { get; set; }
            public List<Product> Products { get; set; }
        }
        public ProductsInChainModel(InventoryDbContext InventoryDbContext)
        {
            this.inventoryDbContext = InventoryDbContext;
        }
        public List<BranchProductViewModel> BranchProducts { get; set; }

        public List<InventorySystem.Models.Product> Products { get; set; }
        public void OnGet(string sortOrder)
        {
            var branches = inventoryDbContext.Branch
                .Where(branch => branch.Name != "Admin")
                .ToList();
            BranchProducts = new List<BranchProductViewModel>();

            foreach (var branch in branches)
            {
                IQueryable<Product> productsQuery = inventoryDbContext.Product
                    .Where(p => p.BranchId == branch.Id);

                switch (sortOrder)
                {
                    case "name":
                        productsQuery = productsQuery.OrderBy(p => p.Name);
                        break;
                    default:
                        productsQuery = productsQuery.OrderByDescending(p => p.ProductId);
                        break;
                }

                var branchProductViewModel = new BranchProductViewModel
                {
                    Branch = branch,
                    Products = productsQuery.ToList()
                };

                BranchProducts.Add(branchProductViewModel);
            }
        }
     
    }
}

Pages/RegisterBranch.cshtml.cs
using InventorySystem.Data;
using InventorySystem.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace InventorySystem.Pages
{
    public class RegisterBranchModel : PageModel
    {
        private readonly InventoryDbContext inventoryDbContext;

        [BindProperty]
        public Branch Branch { get; set; }

        [BindProperty]
        public User User { get; set; }

        public RegisterBranchModel(InventoryDbContext InventoryDbContext)
        {
            this.inventoryDbContext = InventoryDbContext;
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync()
        {

           if (ModelState.IsValid)
            {
                inventoryDbContext.Branch.Add(Branch);
                await inventoryDbContext.SaveChangesAsync();
                User.BranchId = Branch.Id;
                inventoryDbContext.User.Add(User);
                await inventoryDbContext.SaveChangesAsync();
                return RedirectToPage("/MainPage");
            }
           else
            {
               return Page();
            }
            
           
        }
    }
}

Pages/Sale.cshtml.cs
using InventorySystem.Data; 
using InventorySystem.Models; 
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Data.SqlClient; 
using Microsoft.EntityFrameworkCore;

namespace InventorySystem.Pages
{
    public class SaleModel : PageModel
    {
        private readonly InventoryDbContext inventoryDbContext;

        public SaleModel(InventoryDbContext inventoryDbContext)
        {
            this.inventoryDbContext = inventoryDbContext;
        }

        public List<InventorySystem.Models.Product> Products { get; set; }
        public List<InventorySystem.Models.Product> SoldItems { get; set; }
       
        public void OnGet()
        {
            IQueryable<InventorySystem.Models.Product> productsQuery = inventoryDbContext.Product.Where(p => p.Location.Equals(HttpContext.Session.GetString("LoggedInUserName")));
            Products = productsQuery.ToList();
        }

        public string CheckStock(List<InventorySystem.Models.Product> soldItems)
        {
            string message = null;
            foreach (var product in soldItems)
            {
                if (product.Quantity <= product.Threshold)
                {
                    message += product.Name +" barcode: "+ product.ProductId + " left in stock " + product.Quantity + " units. ";
                }
            }
            return message;
        }

        public void OnPostUpdateQuantities()
        {
            SoldItems = new List<InventorySystem.Models.Product>();
            var submittedQuantities = new Dictionary<int, int>(); 

            // Extract submitted quantities from form data
            foreach (var keyValuePair in Request.Form)
            {
                if (keyValuePair.Key.StartsWith("quantity["))
                {
                    var productId = int.Parse(keyValuePair.Key.Split('[')[1].Split(']')[0]);
                    var quantity = int.Parse(keyValuePair.Value);
                    submittedQuantities.Add(productId, quantity);
                }
            }


            foreach (var (productId, quantity) in submittedQuantities)
            {
                var product = inventoryDbContext.Product.FirstOrDefault(p => p.Id == productId);
                if (quantity > 0)
                {
                    SoldItems.Add(product);
                    if (product != null)
                    {
                        product.Quantity -= quantity; 
                        inventoryDbContext.SaveChanges();
                    }
                }
            }

            IQueryable<InventorySystem.Models.Product> productsQuery = inventoryDbContext.Product.Where(p => p.Location.Equals(HttpContext.Session.GetString("LoggedInUserName")));
            Products = productsQuery.ToList();

             ViewData["Message"] = "Sale was made successfully";
            if(SoldItems.Count > 0)
                TempData["StockAlert"] = CheckStock(SoldItems);
        }
        public async Task OnPostAsync()
        {
            var searchString = Request.Form["searchString"];
            Products = await inventoryDbContext.Product.Where(p => p.Location.Equals(HttpContext.Session.GetString("LoggedInUserName"))).Where(p => p.Name.ToLower().Contains(searchString) || p.Description.ToLower().Contains(searchString)).ToListAsync();
        }
    }

   
}

Pages/Search.cshtml.cs
using InventorySystem.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace InventorySystem.Pages
{
    public class SearchModel : PageModel
    {
        private readonly InventoryDbContext inventoryDbContext;

        public SearchModel(InventoryDbContext InventoryDbContext)
        {
            this.inventoryDbContext = InventoryDbContext;
        }

        public List<InventorySystem.Models.Product> Products { get; set; }
        public void OnGet()
        {
            Products = new List<InventorySystem.Models.Product>();
        }

        public async Task OnPostAsync()
        {
            var searchString = Request.Form["searchString"];
            Products = await inventoryDbContext.Product.Where(p => p.Name.ToLower().Contains(searchString) || p.Description.ToLower().Contains(searchString) || p.ProductId.Contains(searchString)).ToListAsync();
        }
    }
}

Pages/Support.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication1.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/AddProduct.cshtml
@page
@model InventorySystem.Pages.AddProductModel
@{
}
<h2 class="text-primary" style="padding: 20px; font-size: 40px; font-weight: bold">Add Product</h2>
<div class="container" style="padding: 30px;">
    <form method="post">
        <div class="form-group row mb-4">
            <div class="col-2">
                <label>Product Name</label>
            </div>
            <div class="col-4">
                <input type="text" id="p-name" class="form-control" asp-for="Product.Name" />
                <span asp-validation-for="Product.Name" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row mb-4">
            <div class="col-2">
                <label>Description</label>
            </div>
            <div class="col-4">
                <input type="text" id="p-description" class="form-control" asp-for="Product.Description" />
                <span asp-validation-for="Product.Description" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row mb-4">
            <div class="col-2">
                <label>Catalog Number</label>
            </div>
            <div class="col-4">
                <input type="text" id="p-catalognumber" class="form-control" asp-for="Product.ProductId" />
                <span asp-validation-for="Product.ProductId" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row mb-4">
            <div class="col-2">
                <label>Quantity</label>
            </div>
            <div class="col-4">
                <input type="text" id="p-quantity" class="form-control" asp-for="Product.Quantity" />
                <span asp-validation-for="Product.Quantity" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row mb-4">
            <div class="col-2">
                <label>Price</label>
            </div>
            <div class="col-4">
                <input type="text" id="p-pricesale" class="form-control" asp-for="Product.PriceCustomer" />
                <span asp-validation-for="Product.PriceCustomer" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row mb-4">
            <div class="col-2">
                <label>Importer Price</label>
            </div>
            <div class="col-4">
                <input type="text" id="p-priceimporter" class="form-control" asp-for="Product.PriceImporter" />
                <span asp-validation-for="Product.PriceImporter" class="text-danger"></span>
            </div>
        </div>

        
            @if (HttpContext.Session.GetString("LoggedInUserName").Equals("Admin"))
            {
            <div class="form-group row mb-4">
                <div class="col-2">
                    <label>Location</label>
                </div>
                <div class="col-4">
                    <select id="b-branch" class="form-select" asp-for="Product.BranchId">
                        @foreach(var branch in Model.Branches)
                        {
                        <option value="@branch.Id">@branch.Name, @branch.Address</option>
                        }
                    </select>
                </div>
             </div>
            }
       

        <div class="form-group row mb-4">
            <div class="col-2">
                <label>Threshold</label>
            </div>
            <div class="col-4">
                <input type="text" id="p-threshold" class="form-control" asp-for="Product.Threshold" />
                <span asp-validation-for="Product.Threshold" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row mb-4">
            <div class="col-2 offset-2">
                <input type="submit" value="Submit" class="btn btn-primary form-control" />
            </div>
        </div>
        <div class="form-group row mb-4">
            <div class="col-2 offset-2">
                <a href="/MainPage" class="btn btn-dark btn-lg">Back</a>
            </div>
        </div>
    </form>
</div>

Pages/EditProduct.cshtml
@page "{id:int}"
@model InventorySystem.Pages.EditProductModel
@{
	var message = ViewData["Message"]?.ToString();
}
<form method="post" onsubmit="return validateForm()">
    <h1 class="text-primary">Edit Product</h1>
    @if (!string.IsNullOrWhiteSpace(message))
    {
        <div class=" alert alert-success" role="alert">
            @message
        </div>
    }
    <div class="mb-3">
        <label class="form-label">Name</label>
        <input type="text" id="p-name" class="form-control" asp-for="EditProduct.Name" value="@Model.EditProduct.Name" readonly/>
    </div>
    <span id="p-name-error" class="text-danger"></span>

    <div class="mb-3">
        <label class="form-label">Description</label>
        <input type="text" id="p-Description" class="form-control" asp-for="EditProduct.Description"  />
    </div>
    <div class="mb-3">
        <label class="form-label">Quantity</label>
        <input type="text" id="p-Quantity" class="form-control" asp-for="EditProduct.Quantity" />
    </div>
    <div class="mb-3">
        <label class="form-label">Price For Customer</label>
        <input type="text" id="p-PriceCustomer" class="form-control" asp-for="EditProduct.PriceCustomer" />
    </div>
    <div class="mb-3">
        <label class="form-label">Threshold</label>
        <input type="text" id="p-Threshold" class="form-control" asp-for="EditProduct.Threshold" />
    </div>


    <div class="mb-3 d-flex justify-content-between">
        <button type="submit" value="Update" class="btn btn-primary" asp-page-handler="Update">
            Update Product
        </button>
        <button type="submit" class="btn btn-danger" asp-page-handler="Delete">
            Delete Product
        </button>
        <a href="/InventoryUpdate" class="btn btn-dark btn-lg">Back</a>


    </div>
</form>

Pages/Index.cshtml
@page
@using InventorySystem.Pages;
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-3" style="color: blue; font-weight: bold;">Welcome To I.M.S - Inventory management system </h1>
    <br /><br />
    <h4>Created by Daniel Shikh & Elizabeth Meirzon </h4>
    <h4>Press the login button to start work </h4>

    <br /><br />

    <a href="/LoginPage" class="btn btn-primary btn-lg">Login</a>

</div>

Pages/InventoryUpdate.cshtml
@page
@model InventorySystem.Pages.InventoryUpdateModel
@{
}
<div class="container row p-0 m-0">
    <div class="col-9">
        <h1 class="text-primary" style="font-weight:bold">Products Table</h1>
    </div>

    <div class="col-12 border p-3 mt-3">
        <div>
            Sort by:
            <a asp-page="./InventoryUpdate" asp-route-sortOrder="name">Product Name</a> |
            <a asp-page="./InventoryUpdate" asp-route-sortOrder="number">Catalog Number</a>
        </div>

        <table class="table table-striped border " style="width:100%">
            <thead>
                <tr>
                    <th>Catalog Number</th>
                    <th>Product Name</th>
                    <th>Description</th>
                    <th>Quantity</th>
                    <th>Price</th>
                    <th>Location</th>
                    <th>Threshold</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var product in Model.Products)
                {
                    <tr>
                        <td>&nbsp&nbsp&nbsp&nbsp @product.ProductId</td>
                        <td>@product.Name</td>
                        <td>@product.Description</td>
                        <td>&nbsp&nbsp&nbsp&nbsp @product.Quantity</td>
                        <td>@product.PriceCustomer</td>
                        <td>@product.Location</td>
                        <td>&nbsp&nbsp&nbsp&nbsp&nbsp @product.Threshold</td>
                        <td>
                            <a href="/EditProduct/@product.Id" class="btn btn-dark">Edit</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="text-center">
        <br />  <a href="/MainPage" class="btn btn-dark btn-lg">Back</a>
    </div>
</div>

Pages/LoginPage.cshtml
@page
@model InventorySystem.Pages.LoginPageModel
@{
    var message = ViewData["Message"]?.ToString();
}

<h1 style="color: blue; text-align: center; font-weight: bold; font-size: 72px;">Login</h1>
<div style="display: flex; justify-content: center;">
    <form method="post">
        <br /><div style="text-align: center;">
            <label for="Username" style="font-size: 18px; font-weight: bold;">Username:</label>
            <br />
            <input type="username" asp-for="UserLogin.UserName" style="font-size: 18px; font-weight: bold;" />
        </div>
        <br /><div style="text-align: center;">
            <label for="Password" style="font-size: 18px; font-weight: bold;">Password:</label>
            <br />
            <input type="password" asp-for="UserLogin.Password" style="font-size: 18px; font-weight: bold;" />
        </div> 
        <br /><br />
        @if (!string.IsNullOrWhiteSpace(message))
        {
            <div class=" alert alert-danger" role="alert">
                @message
            </div>
        }
        <br />  <div class="align-content-center" style="display: flex; justify-content: center;">
            <button type="submit" style="background-color: blue; color: white; font-weight: bold; border: none; padding: 10px 20px;">Login</button>
        </div>
    </form>
</div>

Pages/ProductsInChain.cshtml
@page
@model InventorySystem.Pages.ProductsInChainModel
@{
}

<div class="container row p-0 m-0">
    <div class="col-9">
        <h1 class="text-primary" style="font-weight:bold;font-size: 40px">Products in chain</h1>
    </div><br />

    @foreach(var branchProductViewModel in Model.BranchProducts)
    {
        <br /><div class="col-9">
           <br /> <h3 class="text" style="font-weight:bold">@branchProductViewModel.Branch.Name</h3>
        </div>
        <div class="col-12 border p-3 mt-3">
            <div class="col-12 border p-2 mt-3 d-flex justify-content-between" style="font-size: 20px">
                <div>
                    Sort by:
                    <a asp-page="./ProductsInChain" asp-route-sortOrder="name">Product Name</a> |
                    <a asp-page="./ProductsInChain" asp-route-sortOrder="number">Catalog Number</a>
                </div>
            </div>

            <table class="table table-striped border " style="width:100%">
                <thead>
                    <tr>
                        <th>Catalog Number</th>
                        <th>Product Name</th>
                        <th>Description</th>
                        <th>Quantity</th>
                        <th>Price</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var product in branchProductViewModel.Products)
                    {
                        <tr>
                            <td>&nbsp&nbsp&nbsp&nbsp @product.ProductId</td>
                            <td>@product.Name</td>
                            <td>@product.Description</td>
                            <td>&nbsp&nbsp&nbsp&nbsp @product.Quantity</td>
                            <td>@product.PriceCustomer</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div> <br />

        
    }
    <div class="text-center">
      <br />  <a href="/MainPage" class="btn btn-dark btn-lg">Back</a>
    </div>


</div>

Pages/Sale.cshtml
@page
@model InventorySystem.Pages.SaleModel
@{
    var message = ViewData["Message"]?.ToString();
}
<div class="container row p-0 m-0">
    <div class="col-9">
        <h1 class="text-primary" style="font-weight:bold">Sale simulation</h1>
    </div>
    <div class="col-12 border p-2 mt-3 d-flex justify-content-end" style="font-size: 20px">
        
        <form method="post" class="searchForm">
            <span class="btn-group">
                <input type="text" name="searchString" placeholder="Search Key" />
                <input class="p-1 m-lg-1 btn btn-sm btn-danger" style="border-radius:10px; font-size: 20px; padding: 10px 20px;"
                       type="submit" value="Search" />
            </span>
        </form>
    </div>
    <div class="col-12 border p-3 mt-3">
        <form method="post" asp-page-handler="UpdateQuantities">
            @if (!string.IsNullOrWhiteSpace(message))
            {
                <div class=" alert alert-success" role="alert">
                    @message
                </div>
            }
            <table class="table table-striped border" style="width:100%">
                <thead>
                    <tr>
                        <th>Catalog Number</th>
                        <th>Product Name</th>
                        <th>Description</th>
                        <th>Quantity in stock</th>
                        <th>Quantity</th>
                        <th>Price</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var product in Model.Products)
                    {
                        <tr>
                            <td>&nbsp&nbsp&nbsp&nbsp&nbsp @product.ProductId</td>
                            <td>@product.Name</td>
                            <td>@product.Description</td>
                            <td>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp @product.Quantity</td>
                            <td>
                                <div class="input-group quantity">
                                    <input type="number" class="form-control text-center" value="0" min="0" max="@product.Quantity" name="quantity[@product.Id]">
                                </div>
                            </td>
                            <td>@product.PriceCustomer</td>
                        </tr>
                    }
                </tbody>
            </table>
            <div class="d-flex justify-content-between">
                <button type="submit" class="btn btn-primary">Make Sale</button>
                <a href="/MainPage" class="btn btn-dark btn-lg">Back</a>
            </div>

        </form>
    </div>
</div>

@section Scripts{
    <script type="text/javascript">
        function openAlert(strMessage){
            var myDiv = document.getElementById("ThresholdAlertBody");
            myDiv.innerHTML=strMessage;
            $('#ThresholdAlert').modal('show');
        }

        $(document).ready(function()
        {
            var msg = "@TempData["StockAlert"]";
            if(msg)
                openAlert(msg);
        });
        </script>
}